# Generated by Django 3.2.3 on 2021-05-18 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0001_initial'),
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidade', to='especialidades.especialidade'),
        ),
    ]
