# Generated by Django 3.2.3 on 2021-05-20 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_alter_medico_especialidade'),
        ('agenda', '0003_alter_horario_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to='medicos.medico'),
        ),
    ]
