# Generated by Django 3.2.3 on 2021-05-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_agenda_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('agenda', 'hora')},
        ),
    ]
